language: c

os:
  - linux

dist: focal

addons:
  homebrew:
    update: true
    brewfile: true

  apt:
    packages:
      - autoconf
      - automake
      - build-essential
      - intltool
      - libgoffice-0.10-dev
      - libgsf-1-dev
      - libgtk-3-dev
      - libofx-dev
      - libssl-dev
      - libtool-bin
      - m4

script:
    - echo "export TRAVIS_OS_NAME=$TRAVIS_OS_NAME" > travis-ci/env
    - echo "export CONF=$CONF" >> travis-ci/env

    - . travis-ci/env ; ./travis-ci/travis-autogen.sh ; make
