# Ubuntu 16.04 is not yet available at Travis-CI o use Docker
# https://github.com/travis-ci/travis-ci/issues/5821

# Require trusty for now as it has a more recent version of autoconf
sudo: required

language: c

compiler:
  - clang
  - gcc

services:
  - docker

env:
  - DIST_NAME: debian
    DIST_VERS: testing
    TAG: grisbi

before_install:
    - docker pull ${DIST_NAME}:${DIST_VERS}
    - docker build --rm=true --file=travis-ci/Dockerfile.${DIST_NAME}-${DIST_VERS} --tag=${DIST_NAME}-${DIST_VERS}:${TAG} travis-ci

script:
    - echo "export CC=$CC" > travis-ci/env
    - docker run --volume=`pwd`:/build ${DIST_NAME}-${DIST_VERS}:${TAG}
      /bin/sh -c ". travis-ci/env ; ./travis-ci/travis-autogen.sh ; make"

