# Ubuntu 16.04 is not yet available at Travis-CI o use Docker
# https://github.com/travis-ci/travis-ci/issues/5821

# Require trusty for now as it has a more recent version of autoconf
sudo: required

language: c

services:
    - docker

script:
    - docker pull ubuntu:16.04
    - docker run ubuntu:16.04 /bin/sh -c "apt-get update ; apt-get install autoconf automake libtool-bin m4 intltool libgtk-3-dev libgsf-1-dev libgoffice-0.10-dev git build-essential -y ; cd /root ; git clone --depth=50 --branch=master https://github.com/grisbi/grisbi.git ; cd grisbi ; ./travis-autogen.sh ; make"

