version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\grisbi-src
# Do not build on tags
skip_tags: true
init:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "echo MSYSTEM=%MSYSTEM% > /appveyor.environment"


    c:\msys64\usr\bin\bash -lc "pacman -S unzip --noconfirm"


    c:\msys64\usr\bin\bash -lc "wget -O /nsis.zip \"https://kent.dl.sourceforge.net/project/nsis/NSIS 3/3.03/nsis-3.03.zip\""

    c:\msys64\usr\bin\bash -lc "cd / && unzip nsis.zip"
environment:
  matrix:
  - MSYSTEM: MINGW32
  - MSYSTEM: MINGW64
install:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "cd /c/projects/grisbi-src/share && ./appveyor-install.sh"

    c:\msys64\usr\bin\bash -lc "ls /mingw*/share/glib-2.0/schemas/gschema.dtd"
build_script:
- cmd: c:\msys64\usr\bin\bash -lc "cd /c/projects/grisbi-src/share && ./appveyor-build.sh"
deploy:
- provider: GitHub
  release: v$(appveyor_build_version)
  priv_key:
    secure: 46qABpxCU2/bCoaFhaY7D0VlSfb4UROcnOZ8ZrNKX307+C7431Y+ZhFvgg6wYdTBFDOkeqDBP+2HiODmWUhT4A/wuul7XoCsvKTuXLdDnRAZrN7Db8bHQr2+Ix5bvA7ZC+YrwO4rg75t6nt1f3FDFD3x9zOIlwnsGdSfkEzXsK/ri38aZl5F+MFP30RMMGzQL5lMSxq/8gDPN+ODyJjffnPWWekm2osyBlhFAe226ssEn5lxHLnhXJMjBH/XWpvg2S84iXJfNT4qEbqkq3Nj6xI/nkdiepypPaapJxWMI1/SxrIXjnxvv5BprEP4AVvfRKoqirBvBtcjnCQQi8MOHrN35QHGXZx7eaN2lyHCUSTidgY7c1qx05s3PI1lQuccdy1DJImXvFi1OpVEOKOqrJifPULyHUm753zu269RHexVsM/55Tm2QJfevS7eqLjVsNo0ao+MTq1/EbkE2VZyncxTLkpWyVIfM9NaP0IvInqnI0oVuLsnZbTuYZGKNx5JDj/FS9KqQaITNAkxMC4xBfUiK0Bzr4NneH7/C+00OBub/epSTbeXHP4KWMc3BnPonbhR5HfISen8oZNORRvEvRjSj4XISMf2rurgLL387e/bWIyFLvAK9Bj4SwRGISARAqmGPY4Yn6xBnasmjuh2l8XaRAOPosnyzie8G1oUD+mT3yTk2M18Hv9iffvV+8FmcMg40bcIpVFEEOZu0sFpNb0nTLicr8noAc4hCsdNJ5rZR9jy+tfYBo6D8luMGyOwNAVEmGTCvV8tkEowryhEzfhSYlMq20lh9+74iX6gGrEgjueywQE/oeDKHCuJ4D9FYY2pKYeqOcEDyOcFzcq4X85TMYfYby4py28aTYyqV50HJHyiS5X37d4+YwA+WI3ImtkMSdUYYDbRF5SVTcJvX1LziO4Ut8/NENcl2/OVoCAwLRpB7HweYmxnajIGibe0c1gbUKUjcKi5F+a9PjyTnz9ZO/0mM2PCcu7xiT1K4W5Ag/B8hqlXEc2fwA7PIBJouyxvon4jhaynAI+eM8WXPioQn8YV3pC4JaboUnawihYy6nz9jXepaJ5fCiRSDSTLCLOA4uuXECqdCuidrpWQ5bN8zt3a8V+nLQG+jwqwIb3MpVlWdLXlkUFTHfK9RGs7vaQ0VuOQ9k166aGt6FvUa2txK9ReQMUSNQYAebJprZte9dDgO1N2eoB+3eO+3C71qGRKev5pHi6yoaRVqysVtVZmSZVgQ1xt/ekYaLopD0GkT8F9XHJSfeFZwauNEQXuZoaWr/o+DWfbM5lsX3x7yl43DEpETZplUk4f78aRS8MumhgcXkHzEm790bBB7DFs0ga4v3Gz9KSS4GwSuXLy6WOjgWchsBeIxb3uNExs+tQB0559jv5T4WPUcvgxpkJ+1n8KF5IsV2Uoz6e7l7chK15b1aYRw6QZnWIBRx689WuJipgav/hDp0EDTVpnjds14GLlg2W3cm73uixUDUc7KPwOhipPVxtrZKqK3uGvPy+lyArCEK/sCtqlZuTaCc+ZzENuOqnFWuN1wkv2tCe5STDzafws+XcD/FaIzv3ToNd5K2B5FuTdlqEy+sWfERpOqhqnfqoVil6N19HW7Ff88+jj12YBiDjTjlVci8OyO8RXL0RaHALqi/HnfUWkCW3jQdZ86zvVnBvbWGL0zQj1FQpFSs/dhGwtQ8XPOJp5/GzDYCzDAJjd4QOOIytFQizCBCb25z2+AWl6gJb+K6Ya468EZy63PHDWFJLAJt82Co6MxCmqCwt/4l271rVfuo3QbKy+9C0gasrhlZHavqjOW/fZ4WO08juJtAy96z+cGFjRRZgLciwcG2vx/Y/O/iTBTONJKaQKsbi4fc9WwGG/K1M3DAkhn5vh6uadTlCjQrg3etMdKeP55R8PSBztf9YSdRHTF2uqBCpz59AHt5iJzm8vRXhjPUedCh+vbblhV7F9EskRGkYDbOc9Dfv8BCC9qLUrPGySSYqVP31Qcs9in23+HRJbm9JUnI/Pz49xly/J4649eyeh1I/WCXqYVjGq3WGNLwo95CV57UIeXHBoazUYV4YIdg8ttMz2SqbWHe0KHAxOLfV4v158oP7PPmLKRwsomrxLsg1EVZV3+Ku9Gsqo8YgPiBopQPWFxdy4Das=
  auth_token:
    secure: sZu+i3QuPeW93JlxEBOJ7E1WYsAZQtIsOHVjzftLxkBvBKX/9Akt4GRYUdQWK3/Z
  artifact: grisbi-compil
  draft: false
  prerelease: true
  on:
      branch:
        - msys2-wip2
