version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\grisbi-src
install:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm"

    c:\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-cairo"

    c:\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gtk3"


    c:\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-freetype"

    c:\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-libgsf"
build_script:
- cmd: >-
    rem Setting variable is mandatory so that pkg-config to find

    rem all .pc files. Note that we DO NOT want space after MINGW64


    set MSYSTEM=MINGW64

    c:\msys64\usr\bin\bash -lc "cd /c/projects/grisbi-src/ && ./autogen.sh"


    c:\msys64\usr\bin\bash -lc "cd /c/projects/grisbi-src && ./configure"
    
    
    c:\msys64\usr\bin\bash -lc "cd /c/projects/grisbi-src && v=\`grep PACKAGE_VERSION config.h | cut -f2 -d '\"'\`; Update-AppveyorBuild -Version "\$v-B{build}"


    c:\msys64\usr\bin\bash -lc "cd /c/projects/grisbi-src && make -j 4"
