version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\grisbi-src
# Do not build on tags
skip_tags: true
init:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "echo MSYSTEM=%MSYSTEM% > /appveyor.environment"


    c:\msys64\usr\bin\bash -lc "pacman -S unzip --noconfirm"


    c:\msys64\usr\bin\bash -lc "wget -O /nsis.zip \"https://kent.dl.sourceforge.net/project/nsis/NSIS 3/3.03/nsis-3.03.zip\""

    c:\msys64\usr\bin\bash -lc "cd / && unzip nsis.zip"
environment:
  matrix:
  - MSYSTEM: MINGW32
  - MSYSTEM: MINGW64
install:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "cd /c/projects/grisbi-src/share && ./appveyor-install.sh"

    c:\msys64\usr\bin\bash -lc "ls /mingw*/share/glib-2.0/schemas/gschema.dtd"
build_script:
- cmd: c:\msys64\usr\bin\bash -lc "cd /c/projects/grisbi-src/share && ./appveyor-build.sh"
deploy:
- provider: GitHub
  release: v$(appveyor_build_version)
  auth_token:
    secure: pA+9wc/rBKc0DNBfVvyxXrJ9+OU++uwZkCzsEtUaTHUDSw5hfpJlIulqq0LcDv3n
  artifact: grisbi-compil
  draft: false
  prerelease: true
  on:
      branch:
        - master
